packages:
  - 'core/packages/*'
  - 'marketplace'
  - 'marketplace/modules/*'

onlyBuiltDependencies:
  - electron
  - esbuild

overrides:
  brace-expansion@<1.1.16: 1.1.16
  brace-expansion@>=5.0.0 <=5.0.7: 5.0.8
  ip-address: 10.1.1
  javascript-obfuscator>multimatch: 8.0.0
  undici: 6.27.0
