name: Feature Request
description: Suggest an idea or request a feature
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve and why does it matter?
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How would you like this to work? Include UI/UX ideas if relevant.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives (optional)
      placeholder: '...'
